In [8]:
df.select_dtypes(include="object").columns

C:\Users\alajo\AppData\Local\Temp\ipykernel_22868\1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['person_home_ownership', 'loan_intent', 'loan_grade',
       'cb_person_default_on_file'],
      dtype='str')

In [9]:
df["person_emp_length"] = df["person_emp_length"].fillna(
    df["person_emp_length"].median()
)

df["loan_int_rate"] = df["loan_int_rate"].fillna(
    df["loan_int_rate"].median()
)

df.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["person_home_ownership"] = le.fit_transform(df["person_home_ownership"])
df["loan_intent"] = le.fit_transform(df["loan_intent"])
df["loan_grade"] = le.fit_transform(df["loan_grade"])
df["cb_person_default_on_file"] = le.fit_transform(df["cb_person_default_on_file"])

df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,3,123.0,4,3,35000,16.02,1,0.59,1,3
1,21,9600,2,5.0,1,1,1000,11.14,0,0.10,0,2
2,25,9600,0,1.0,3,2,5500,12.87,1,0.57,0,3
3,23,65500,3,4.0,3,2,35000,15.23,1,0.53,0,2
4,24,54400,3,8.0,3,2,35000,14.27,1,0.55,1,4

In [6]:
df["loan_status"].value_counts()

loan_status
0    25473
1     7108
Name: count, dtype: int64

In [5]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [4]:
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  int64
 3   person_emp_length           32581 non-null  float64
 4   loan_intent                 32581 non-null  int64
 5   loan_grade                  32581 non-null  int64
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               32581 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  int64
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(9)
memory usage: 3.0 MB

In [13]:
X = df.drop("loan_status", axis=1)
y = df["loan_status"]

print(X.shape)
print(y.shape)

(32581, 11)
(32581,)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data :", X_test.shape)

Training Data: (26064, 11)
Testing Data : (6517, 11)

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train[:5])

[[ 5.66851795 -0.31717677  0.92404561 -0.68213538  0.84992295  0.6746644
  -0.76018887  0.02663141 -0.65843875  2.17447733  4.48497655]
 [-0.27606233 -0.63165151  0.22625263 -1.17543958 -1.45948223  2.39492002
  -0.17434095  1.77173414  1.49131123 -0.45988063 -0.69475502]
 [-0.7453713  -0.23855808 -1.16933334 -0.43548328  0.84992295  0.6746644
   1.01318862  0.68430072  1.30437645  2.17447733 -0.69475502]
 [-0.90180763 -0.1598765  -1.16933334  0.30447301  0.27257166 -1.04559122
  -0.57018414 -1.01847675 -0.56497136 -0.45988063 -0.44810114]
 [-0.58893498  0.20170655  0.92404561 -0.43548328  0.84992295  0.6746644
  -0.41184686  0.49872077 -0.75190614 -0.45988063 -0.69475502]]

In [16]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

print("Model Trained Successfully!")

Model Trained Successfully!

In [17]:
y_pred = model.predict(X_test)

print("Predicted:", y_pred[:10])
print("Actual   :", y_test[:10].values)

Predicted: [1 0 0 0 1 0 0 0 0 0]
Actual   : [0 0 0 1 1 0 0 0 0 0]

In [18]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8371950283872948

In [19]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[4820  252]
 [ 809  636]]

In [21]:
import pickle

with open("../models/credit_scoring_model.pkl", "wb") as file:
    pickle.dump(model, file)

with open("../models/scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

print("Model Saved Successfully!")
print("Scaler Saved Successfully!")

Model Saved Successfully!
Scaler Saved Successfully!

In [20]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.95      0.90      5072
           1       0.72      0.44      0.55      1445

    accuracy                           0.84      6517
   macro avg       0.79      0.70      0.72      6517
weighted avg       0.83      0.84      0.82      6517

In [2]:
df.shape

(32581, 12)

In [1]:
import pandas as pd

df = pd.read_csv("../data/credit_risk_dataset.csv")

df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4